title: Gabriel blog
author: gabri47
description: On this page, I will write writeups of the machines I make.
google_analytics:  
google_site_verification_content: 
disqus_forum_shortname: captainirs-github-io

#Usernames and badges
htb_badge_no: 831031
thm_badge_no:
show_thm_htb_badges_in_nav: true 
github_username: GabrielGonzalez211
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: 
twitch:
youtube:
twitter: 
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
include:
  - googleb332967695d7df88.html
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true
